language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
before_script:
  - chmod +x scripts/docs
script:
  - npm test -- --coverage
after_script:
  - npm run coverage
after_success:
  - scripts/docs
env:
  global:
    secure: fake
branches:
  only:
    - master
